# Generated by Django 4.2 on 2024-01-30 22:01

import appi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=appi.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
